In [1]:
# 타이타닉 호 승객 생존 예측 미니 프로젝트 : 2. 전처리

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('titanic.csv')
df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1305,3.0,0.0,"Zabour, Miss. Thamine",female,NaN,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3.0,0.0,"Zakarian, Mr. Mapriededer",male,26.5000,0.0,0.0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3.0,0.0,"Zakarian, Mr. Ortin",male,27.0000,0.0,0.0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3.0,0.0,"Zimmerman, Mr. Leo",male,29.0000,0.0,0.0,315082,7.8750,NaN,S,NaN,NaN,NaN
1309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.info()
# sex(Dtype이 object)을 숫자로 바꾸자.
# age의 263개의 결측치를 채우자
# fare(운임)의 1개의 결측치는 버리자.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1310 entries, 0 to 1309
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   float64
 1   survived   1309 non-null   float64
 2   name       1309 non-null   object
 3   sex        1309 non-null   object
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   float64
 6   parch      1309 non-null   float64
 7   ticket     1309 non-null   object
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object
 10  embarked   1307 non-null   object
 11  boat       486 non-null    object
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object
dtypes: float64(7), object(7)
memory usage: 143.4+ KB

In [6]:
# sex을 숫자로 변경
# df['추가할_컬럼'] = 계산식
df['sex2'] = df['sex'].map( {'female':1, 'male':0} )
df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,sex2
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO",1.0
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON",0.0
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON",1.0
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON",0.0
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON",1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1305,3.0,0.0,"Zabour, Miss. Thamine",female,NaN,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN,1.0
1306,3.0,0.0,"Zakarian, Mr. Mapriededer",male,26.5000,0.0,0.0,2656,7.2250,NaN,C,NaN,304.0,NaN,0.0
1307,3.0,0.0,"Zakarian, Mr. Ortin",male,27.0000,0.0,0.0,2670,7.2250,NaN,C,NaN,NaN,NaN,0.0
1308,3.0,0.0,"Zimmerman, Mr. Leo",male,29.0000,0.0,0.0,315082,7.8750,NaN,S,NaN,NaN,NaN,0.0
1309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# 운임(fare)의 결측치 삭제
df = df.dropna(subset=['fare'])
df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,sex2
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO",1.0
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON",0.0
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON",1.0
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON",0.0
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON",1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3.0,0.0,"Zabour, Miss. Hileni",female,14.5000,1.0,0.0,2665,14.4542,NaN,C,NaN,328.0,NaN,1.0
1305,3.0,0.0,"Zabour, Miss. Thamine",female,NaN,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN,1.0
1306,3.0,0.0,"Zakarian, Mr. Mapriededer",male,26.5000,0.0,0.0,2656,7.2250,NaN,C,NaN,304.0,NaN,0.0
1307,3.0,0.0,"Zakarian, Mr. Ortin",male,27.0000,0.0,0.0,2670,7.2250,NaN,C,NaN,NaN,NaN,0.0
1308,3.0,0.0,"Zimmerman, Mr. Leo",male,29.0000,0.0,0.0,315082,7.8750,NaN,S,NaN,NaN,NaN,0.0

In [8]:
# name 컬럼에서 호칭을 뽑아내자. 예) Miss. ==> Miss
# df['추가할_컬럼'] = 계산식
df['title'] = df['name'].str.extract("([A-Za-z]+)\.") # 정규표현식
df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,sex2,title
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO",1.0,Miss
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON",0.0,Master
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON",1.0,Miss
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON",0.0,Mr
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON",1.0,Mrs
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3.0,0.0,"Zabour, Miss. Hileni",female,14.5000,1.0,0.0,2665,14.4542,NaN,C,NaN,328.0,NaN,1.0,Miss
1305,3.0,0.0,"Zabour, Miss. Thamine",female,NaN,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN,1.0,Miss
1306,3.0,0.0,"Zakarian, Mr. Mapriededer",male,26.5000,0.0,0.0,2656,7.2250,NaN,C,NaN,304.0,NaN,0.0,Mr
1307,3.0,0.0,"Zakarian, Mr. Ortin",male,27.0000,0.0,0.0,2670,7.2250,NaN,C,NaN,NaN,NaN,0.0,Mr
1308,3.0,0.0,"Zimmerman, Mr. Leo",male,29.0000,0.0,0.0,315082,7.8750,NaN,S,NaN,NaN,NaN,0.0,Mr

In [9]:
df[df["name"].str.contains(r"Dona\.", na=False)]

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,sex2,title
218,1.0,1.0,"Oliva y Ocana, Dona. Fermina",female,39.0,0.0,0.0,PC 17758,108.9,C105,C,8,NaN,NaN,1.0,Dona

In [10]:
df['title'].unique()

array(['Miss', 'Master', 'Mr', 'Mrs', 'Col', 'Mme', 'Dr', 'Major', 'Capt',
       'Lady', 'Sir', 'Mlle', 'Dona', 'Jonkheer', 'Countess', 'Don',
       'Rev', 'Ms'], dtype=object)

In [11]:
print( sorted( df['title'].unique() ) )

['Capt', 'Col', 'Countess', 'Don', 'Dona', 'Dr', 'Jonkheer', 'Lady', 'Major', 'Master', 'Miss', 'Mlle', 'Mme', 'Mr', 'Mrs', 'Ms', 'Rev', 'Sir']

In [12]:
df['title'].value_counts()

title
Mr          756
Miss        260
Mrs         197
Master       61
Rev           8
Dr            8
Col           4
Mlle          2
Ms            2
Major         2
Capt          1
Sir           1
Dona          1
Jonkheer      1
Countess      1
Don           1
Mme           1
Lady          1
Name: count, dtype: int64

<style>
/* Notebook markdown 영역을 왼쪽 정렬로 강제 */
div.text_cell_render {
    text-align: left !important;
}

/* Markdown의 <p>, <ul>, <ol>도 왼쪽 정렬로 강제 */
div.text_cell_render p,
div.text_cell_render ul,
div.text_cell_render ol {
    text-align: left !important;
}
</style>

In [13]:
%%html
<style>
table {float: left;}
</style>

| Title        | Gender     | Marital Status  | Meaning / Origin (설명)             |
| ------------ | ---------- | --------------- | --------------------------------- |
| **Capt**     | Male       | Unknown         | **Captain** — 선장 또는 군대 장교 계급      |
| **Col**      | Male       | Unknown         | **Colonel** — 육군 대령 계급            |
| **Countess** | Female     | Married / Noble | **Countess** — 백작의 아내 또는 여성 귀족    |
| **Don**      | Male       | Unknown (귀족/신사) | **Don** — 스페인·이탈리아 귀족/높은 신분 남성 칭호 |
| **Dona**     | Female     | Unknown (귀족)    | **Dona** — 스페인·포르투갈 귀부인, 여성 귀족 칭호 |
| **Dr**       | Male (대부분) | Unknown         | **Doctor** — 전문직 직업 호칭            |
| **Jonkheer** | Male       | **Single**      | 네덜란드 귀족 칭호, 주로 미혼 남성에게 사용         |
| **Lady**     | Female     | Married / Noble | 영국 귀족 여성 칭호 (기혼 또는 사교계 귀부인)       |
| **Major**    | Male       | Unknown         | **Major** — 군 계급 (소령)             |
| **Master**   | Male       | **Single (소년)** | 소년·남자 아이에게만 사용되는 호칭               |
| **Miss**     | Female     | **Single**      | 미혼 여성                             |
| **Mlle**     | Female     | **Single**      | 프랑스어 Miss → *Mademoiselle*        |
| **Mme**      | Female     | **Married**     | 프랑스어 Mrs → *Madame*               |
| **Mr**       | Male       | Unknown         | 성인 남성 일반 호칭 (미혼/기혼 모두 가능)         |
| **Mrs**      | Female     | **Married**     | 기혼 여성 (Married Woman)             |
| **Ms**       | Female     | Unknown         | 현대적 중립형 여성 호칭 (Titanic에서는 대부분 여성) |
| **Rev**      | Male       | Unknown         | **Reverend** — 성직자 호칭 (대부분 남성)    |
| **Sir**      | Male       | Unknown         | 기사 작위(나이트) 남성에게 부여되는 칭호           |

In [14]:
# 5개로 통합 : Master(아이), Miss, Mr, Mrs, Other(기타)
before = ['Capt', 'Col', 'Countess', 'Don', 'Dona',
          'Dr', 'Jonkheer', 'Lady', 'Major', 'Mlle',
          'Mme', 'Ms', 'Rev', 'Sir']
after  = ['Mr', 'Mr', 'Mrs', 'Mr', 'Miss',
          'Other', 'Mr', 'Mrs', 'Mr', 'Miss',
          'Mrs', 'Miss', 'Other', 'Mr']
df['title2'] = df['title'].replace( before, after )
df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,sex2,title,title2
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO",1.0,Miss,Miss
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON",0.0,Master,Master
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON",1.0,Miss,Miss
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON",0.0,Mr,Mr
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON",1.0,Mrs,Mrs
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3.0,0.0,"Zabour, Miss. Hileni",female,14.5000,1.0,0.0,2665,14.4542,NaN,C,NaN,328.0,NaN,1.0,Miss,Miss
1305,3.0,0.0,"Zabour, Miss. Thamine",female,NaN,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN,1.0,Miss,Miss
1306,3.0,0.0,"Zakarian, Mr. Mapriededer",male,26.5000,0.0,0.0,2656,7.2250,NaN,C,NaN,304.0,NaN,0.0,Mr,Mr
1307,3.0,0.0,"Zakarian, Mr. Ortin",male,27.0000,0.0,0.0,2670,7.2250,NaN,C,NaN,NaN,NaN,0.0,Mr,Mr
1308,3.0,0.0,"Zimmerman, Mr. Leo",male,29.0000,0.0,0.0,315082,7.8750,NaN,S,NaN,NaN,NaN,0.0,Mr,Mr

In [15]:
df['title2'].value_counts()

title2
Mr        766
Miss      265
Mrs       200
Master     61
Other      16
Name: count, dtype: int64

In [16]:
# 예) title2 가 'Master' 이면서(&) 나이(age)가 결측치인 데이터 확인
# df.loc[ 조건, 컬럼명 ]
df.loc[ (df['title2'] == 'Master') & (df['age'].isnull()),  ]

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,sex2,title,title2
672,3.0,0.0,"Betros, Master. Seman",male,NaN,0.0,0.0,2622,7.2292,NaN,C,NaN,NaN,NaN,0.0,Master,Master
900,3.0,0.0,"Johnston, Master. William Arthur ""Willie""",male,NaN,1.0,2.0,W./C. 6607,23.4500,NaN,S,NaN,NaN,NaN,0.0,Master,Master
954,3.0,0.0,"Lefebre, Master. Henry Forbes",male,NaN,3.0,1.0,4133,25.4667,NaN,S,NaN,NaN,NaN,0.0,Master,Master
1034,3.0,1.0,"Moubarek, Master. Gerios",male,NaN,1.0,1.0,2661,15.2458,NaN,C,C,NaN,NaN,0.0,Master,Master
1035,3.0,1.0,"Moubarek, Master. Halim Gonios (""William George"")",male,NaN,1.0,1.0,2661,15.2458,NaN,C,C,NaN,NaN,0.0,Master,Master
1121,3.0,1.0,"Peter, Master. Michael J",male,NaN,1.0,1.0,2668,22.3583,NaN,C,C,NaN,NaN,0.0,Master,Master
1170,3.0,0.0,"Sage, Master. Thomas Henry",male,NaN,8.0,2.0,CA. 2343,69.5500,NaN,S,NaN,NaN,NaN,0.0,Master,Master
1262,3.0,0.0,"van Billiard, Master. James William",male,NaN,1.0,1.0,A/5. 851,14.5000,NaN,S,NaN,NaN,NaN,0.0,Master,Master

In [17]:
df.loc[ (df['title2'] == 'Master') & (df['age'].isnull()), 'age' ]

672    NaN
900    NaN
954    NaN
1034   NaN
1035   NaN
1121   NaN
1170   NaN
1262   NaN
Name: age, dtype: float64

In [18]:
# 호칭(title2)별 나이의 평균
df.groupby('title2')['age'].mean()

title2
Master     5.482704
Miss      21.904595
Mr        32.522034
Mrs       36.959538
Other     42.333333
Name: age, dtype: float64

In [19]:
df.loc[ (df['title2'] == 'Master') & (df['age'].isnull()), 'age' ] = 5.48
df.loc[ (df['title2'] == 'Miss') & (df['age'].isnull()), 'age' ] = 21.9
df.loc[ (df['title2'] == 'Mr') & (df['age'].isnull()), 'age' ] = 32.52
df.loc[ (df['title2'] == 'Mrs') & (df['age'].isnull()), 'age' ] = 36.95
df.loc[ (df['title2'] == 'Other') & (df['age'].isnull()), 'age' ] = 42.33

In [20]:
df.isnull().sum() # age    0 <== age 결측치 채우기 성공

pclass          0
survived        0
name            0
sex             0
age             0
sibsp           0
parch           0
ticket          0
fare            0
cabin        1013
embarked        2
boat          822
body         1188
home.dest     563
sex2            0
title           0
title2          0
dtype: int64

In [21]:
# 저장
df.to_csv('titanic_ok.csv', index=False)

In [22]:
# 잘 저장되었는지 체크
df2 = pd.read_csv('titanic_ok.csv')
df2

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,sex2,title,title2
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO",1.0,Miss,Miss
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON",0.0,Master,Master
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON",1.0,Miss,Miss
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON",0.0,Mr,Mr
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON",1.0,Mrs,Mrs
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1303,3.0,0.0,"Zabour, Miss. Hileni",female,14.5000,1.0,0.0,2665,14.4542,NaN,C,NaN,328.0,NaN,1.0,Miss,Miss
1304,3.0,0.0,"Zabour, Miss. Thamine",female,21.9000,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN,1.0,Miss,Miss
1305,3.0,0.0,"Zakarian, Mr. Mapriededer",male,26.5000,0.0,0.0,2656,7.2250,NaN,C,NaN,304.0,NaN,0.0,Mr,Mr
1306,3.0,0.0,"Zakarian, Mr. Ortin",male,27.0000,0.0,0.0,2670,7.2250,NaN,C,NaN,NaN,NaN,0.0,Mr,Mr
1307,3.0,0.0,"Zimmerman, Mr. Leo",male,29.0000,0.0,0.0,315082,7.8750,NaN,S,NaN,NaN,NaN,0.0,Mr,Mr

In [23]:
# end